/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Sion
 */
public class JIConsultaT extends javax.swing.JInternalFrame {
JDesktopPane des;
Connection ObjBD;
    /**
     * Creates new form JIConsultaT
     */
     public JIConsultaT(JDesktopPane desk, Connection o) {
        initComponents();
        des=desk;
        ObjBD=o;
    }
    public JIConsultaT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdTicket = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblIdTicket = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNueva = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Ingrese el Numero de Ticket");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo del Ticket");

        jLabel3.setText("Fecha Ingreso ");

        jLabel4.setText("Costo");

        btnNueva.setText("Nueva Busqueda");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(90, 90, 90))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIdTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(63, 63, 63))
                            .addComponent(lblFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNueva)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addComponent(btnNueva)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    try {
        String consulta ="Select  Id_Ticket, FechaIngreso_T, FechaSalida_T, Costo_T from ticket where Id_Ticket="+this.txtIdTicket.getText();
        PreparedStatement str = ObjBD.prepareStatement(consulta);
        ResultSet resultado=str.executeQuery();
        while(resultado.next()){
            this.lblIdTicket.setText(resultado.getString("Id_Ticket"));
            this.lblFechaIngreso.setText(resultado.getString("FechaIngreso_T"));
            if(resultado.getString("FechaSalida_T")==null)
            {
                this.lblFechaSalida.setText("No ha salido del Parqueadero");
                String fec=this.lblFechaIngreso.getText();
                int año,mes,dia,horas,min,sec;
                String fec1[]= fec.split(" ");
                String fecha=fec1[0];
                String fecha2=fec1[1];
                String aux[]=fecha.split("-");
                String aux2[]=fecha2.split(":");
                año=Integer.parseInt(aux[0]);
                mes=Integer.parseInt(aux[1]);
                dia=Integer.parseInt(aux[2]);
                horas=Integer.parseInt(aux2[0]);
                min=Integer.parseInt(aux2[1]);
            
                Calendar Cal= Calendar.getInstance();
                int minutoD=(Cal.get(Cal.MINUTE)), mesD=Cal.get(Cal.MONTH)+1;
                int canthoras=0,cantdias=0;
                double costo=0,costototal=0;
                if(año==Cal.get(Cal.YEAR))                
                    {   
                    System.out.println("Entro hasta años "+mes+"\n"+mesD);
                    if(mes==mesD)
                    {
                        System.out.println("Engtro hasta meses");
                        if(dia==Cal.get(Cal.DATE))
                        {
                            System.out.println("Entro hasta dias");
                            if(horas==Cal.get(Cal.HOUR_OF_DAY))
                            {   
                                
                                System.out.println("Entro hasta horas");
                            }
                        else{
                            canthoras=Cal.get(Cal.HOUR_OF_DAY)-horas;
                            canthoras=canthoras*2000;
                            costototal=costototal+canthoras;
                            System.out.println("Entro hasta ELSE1");
                        }
                        }
                    else{
                        cantdias=Cal.get(Cal.DATE)-dia;
                        cantdias=cantdias*12000;
                        costototal+=cantdias;
                        System.out.println("Entro hasta ELSE2");
                    }
                    }
                }
            if(minutoD>min)
                {
                costo=minutoD-min;
                costo=costo*75;
                System.out.println("Entro hasta minuto"+costo);
                }else{
            if(min>minutoD){
                costo=min-minutoD;
                costo=costo*75;
                System.out.println("Entro MINUTO"+costo);
            }
            
            }
            costototal=costototal+costo;
            System.out.println("El valor del total es"+costototal);
            JOptionPane.showMessageDialog(this, "El valor de Fecha 1 es"+fecha+"\nEl valor de fecha2 es"+fecha2);
            this.lblCosto.setText(""+costototal);
        }else{
        this.lblFechaSalida.setText(resultado.getString("FechaSalida_T"));
        this.lblCosto.setText(resultado.getString("Costo_T"));}
        }
        
        
    }catch(SQLException ex){
        Logger.getLogger(JITicket.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        // TODO add your handling code here:
        this.txtIdTicket.setText("");
        this.lblCosto.setText("");
        this.lblFechaIngreso.setText("");
        this.lblIdTicket.setText("");
        this.lblFechaSalida.setText("");
    }//GEN-LAST:event_btnNuevaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblIdTicket;
    private javax.swing.JTextField txtIdTicket;
    // End of variables declaration//GEN-END:variables
}
