/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Conexion.ConexionBD;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Sion
 */
public class JITicket extends javax.swing.JInternalFrame {
JDesktopPane des;
Connection ObjBD;
Statement str,str2;
ResultSet resultado;
String fec;
int valorEntero;
    /**
     * Creates new form JITicket
     */
    public JITicket(JDesktopPane desk, Connection BD) throws SQLException {
        initComponents();
        des=desk;
        ObjBD=BD;
        str=ObjBD.createStatement();
        this.btnPDF.setEnabled(false);
    }
    public JITicket() throws SQLException {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCodTicket = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Codigo Ticket");

        jLabel2.setText("Ingrese los siguientes Datos");

        btnRegistrar.setText("Generar Ticket");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnPDF.setText("Imprimir PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71)))
                        .addGap(80, 80, 80)
                        .addComponent(lblCodTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPDF)
                            .addComponent(btnRegistrar))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(btnRegistrar)
                .addGap(60, 60, 60)
                .addComponent(btnPDF)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
   try {
        valorEntero= (int) Math.floor(Math.random()*(1-99999+1)+99999);
        
        String consulta="select Id_Ticket from ticket where Id_Ticket = "+valorEntero;
        str2=ObjBD.prepareStatement(consulta);
        resultado=str2.executeQuery(consulta);
        if(resultado.getRow()>0)
        {
            
            int auxiliar=Integer.parseInt(resultado.getString("Id_Ticket"));
            
            while(resultado.next()){
                if(valorEntero==auxiliar);
                valorEntero = (int) Math.floor(Math.random()*(1-99999+1)+99999);
                
            }
        }else{
            this.lblCodTicket.setText(""+valorEntero);
            Calendar Cal= Calendar.getInstance(); 
            fec= Cal.get(Cal.YEAR)+"-"+(Cal.get(Cal.MONTH)+1)+"-"+Cal.get(Cal.DATE)+" "+Cal.get(Cal.HOUR_OF_DAY)+":"+Cal.get(Cal.MINUTE)+":"+Cal.get(Cal.SECOND); 
            JOptionPane.showMessageDialog(this,"La fecha del ticket es "+ fec);
            String insercion = "Insert into Ticket  (id_ticket, fechaingreso_t,pagado_T) values ("+valorEntero+",'"+fec+"',0);";
            str.executeUpdate(insercion);
            JOptionPane.showMessageDialog(this,"Ticket Registrado con Exito \n No olvide guardar su No de Ticket");
            this.btnPDF.setEnabled(true);
        }
    } catch (SQLException ex) {
        Logger.getLogger(JITicket.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        ArchPdf obj;
        obj=new ArchPdf();
        obj.crear_PDF(Integer.parseInt(this.lblCodTicket.getText()), fec);
    }//GEN-LAST:event_btnPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCodTicket;
    // End of variables declaration//GEN-END:variables
}
